# Generated by Django 2.2.13 on 2021-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_sales', models.CharField(max_length=1000)),
                ('open_hours', models.IntegerField(max_length=10)),
            ],
        ),
    ]
