# Generated by Django 2.2.13 on 2021-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_stores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='store_sales',
        ),
        migrations.AddField(
            model_name='stores',
            name='store_rating',
            field=models.IntegerField(default=5, max_length=5),
            preserve_default=False,
        ),
    ]
